# Data processing script with .npz script for compiling input channel = x, \Gamma, \sigma, u(x_p); and 
# output channel_1 = \delta{x}, \delta{\Gamma}, \delta{\sigma}, \delta{u(x_p)}. 
# output channel_2 = u(x)

from __future__ import annotations
import json
import os
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import h5py
import numpy as np

try:
    from scipy.spatial import cKDTree

    SCIPY_AVAILABLE = True
except Exception:
    SCIPY_AVAILABLE = False

try:
    import pyvista as pv

    PYVISTA_AVAILABLE = True
except Exception:
    PYVISTA_AVAILABLE = False


SCRIPT_DIR = Path(__file__).resolve().parent

# Task-1 dataset root
RAW_ROOT = Path("/media/neerajc/New Volume/Neeraj/neuralop/data/task1")
RAW_ROOT_CANDIDATES = [RAW_ROOT]
FIELD_ROOT = Path("/media/neerajc/New Volume/Neeraj/neuralop/data/task2")
FIELD_ROOT_CANDIDATES = [FIELD_ROOT]

# Leave empty when AUTO_DISCOVER_TASK1_CASES=True.
DATASET_IDS: List[str] = []
AUTO_DISCOVER_TASK1_CASES = True
AUTO_ASSIGN_SPLITS_FROM_CASE_NAMES = True

# Case-name format generated by the current bash pipeline.
TASK1_CASE_RE = re.compile(r"^(?P<aoa>\d+(?:\.\d+)?)deg_static_airfoil_(?P<speed>\d+(?:\.\d+)?)u_(?P<particles>\d+)p$")

# AoA plan for the methodical dataset generation.
TRAIN_AOA_DEGREES = list(range(10, 31, 2))
VAL_AOA_DEGREES = [11, 15, 21, 25]
TEST_AOA_DEGREES = [27, 32]
IGNORE_AOA_DEGREES = [19]
TEST_NORMAL_AOA_DEGREES = [27]
TEST_SUPER_RESOLUTION_AOA_DEGREES: List[int] = []
TEST_UNSEEN_AOA_DEGREES = [32]
DEFAULT_PARTICLES_PER_STEP = 1
EXPECTED_PARTICLES_PER_STEP_BY_AOA: Dict[int, int] = {}

# Direct-per-case file patterns.
DYNAMIC_PARTICLE_H5_PATTERN = "static_airfoil_pfield.*.h5"
STATIC_PARTICLE_H5_PATTERN = "static_airfoil_staticpfield.*.h5"
VTK_PATTERN = "static_airfoil_Wing_vlm.*.vtk"
FIELD_H5_PATTERN = "static_airfoil_fdom.*.h5"
INCLUDE_STATIC_PARTICLES = True

OUT_ROOT = SCRIPT_DIR / "processed_data"
MERGED_ROOT = OUT_ROOT / "merged_frames"

# Task-1 evolution setup
RANDOM_SEED = 42
TASK1_TARGET_MODE = "delta"

# Optional metadata table path for strict conditioning channels.
#
# For the current automated Task-1 folders, this file is OPTIONAL because
# metadata is inferred directly from folder names such as:
#   10deg_static_airfoil_10u_1p
# which means:
#   AoA = 10 deg, freestream magnitude = 10 m/s, particles_per_step = 1.
#
# If a future case does not follow that naming convention, or if one case has
# a special dt/freestream, put overrides in this JSON file:
# {
#   "10deg_static_airfoil_10u_1p": {"aoa_deg": 10.0, "magVinf": 10.0, "dt": 0.0034},
#   "custom_case_name": {"aoa_deg": 18.0, "freestream": [9.51, 0.0, 3.09], "dt": 0.0034}
# }
CASE_METADATA_PATH = SCRIPT_DIR / "case_metadata.json"
STRICT_METADATA_VALIDATION = True

# Inline table for manual metadata overrides. Leave empty for the current
# generated data because _prepare_case_metadata() auto-fills AoA/freestream
# from folder names and uses DEFAULT_TASK1_DT.
CASE_METADATA: Dict[str, Dict[str, Any]] = {}
DEFAULT_TASK1_DT = 0.0034 # Find out if this is the case.

# Split by CASE (or AoA groups) to avoid temporal leakage.
# Example desired pattern:
#   TRAIN_CASES = ["1", "2", "7"]
#   VAL_CASES   = ["8"]
#   TEST_CASES  = ["9"]
TRAIN_CASES: List[str] = []
VAL_CASES: List[str] = []
TEST_CASES: List[str] = []
# AUTO_ASSIGN_SPLITS_FROM_CASE_NAMES = True - above will be assigned automatically.

# Feature/state definitions for Task-1 evolution.
STATE_NAMES = ["x", "y", "z", "Gamma_x", "Gamma_y", "Gamma_z", "sigma"]
TARGET_DELTA_NAMES = [
    "dx",
    "dy",
    "dz",
    "dGamma_x",
    "dGamma_y",
    "dGamma_z",
    "dsigma",
    "delta_u_x",
    "delta_u_y",
    "delta_u_z",
]

# Field-reconstruction supervision for the MLP decoder.  These query points come
# from the precomputed task2 field grid, not from particle positions.
MAX_FIELD_QUERY_POINTS = 4096
FIELD_TARGET_NAMES = ["u_x", "u_y", "u_z"]

# Geometry-aware particle channels (from per-frame VTK).
USE_GEOMETRY_CHANNELS = True
GEOMETRY_NEAR_THRESHOLD = 0.02
GEOMETRY_CHANNEL_NAMES = [
    "geom_dist",
    "geom_nx",
    "geom_ny",
    "geom_nz",
    "geom_body_near",
]

# Explicit per-frame conditioning channels appended to each particle feature.
# c_n = [alpha_n, U_inf,n, phi_n, geometry embedding]
USE_EXPLICIT_CONDITIONING = True
CONDITIONING_CHANNEL_NAMES = [
    "angle_of_attack",
    "freestream_x",
    # "freestream_y",
    "freestream_z",
    "phase",
]

PARTICLE_INPUT_FEATURES = [
    "x",
    "y",
    "z",
    "Gamma_x",
    "Gamma_y",
    "Gamma_z",
    "sigma",
    "u_x",
    "u_y",
    "u_z",
]
if USE_GEOMETRY_CHANNELS:
    PARTICLE_INPUT_FEATURES = PARTICLE_INPUT_FEATURES + GEOMETRY_CHANNEL_NAMES
if USE_EXPLICIT_CONDITIONING:
    PARTICLE_INPUT_FEATURES = PARTICLE_INPUT_FEATURES + CONDITIONING_CHANNEL_NAMES

# Frame quality control.
MIN_PARTICLES_PER_FRAME = 64 # See what is the use and keep a value > 300
EXPORT_FILTERED_FRAME_MANIFEST = True

# Geometry QA control.
STRICT_GEOMETRY_QA = True
GEOM_MIN_NONZERO_FRAC = 1e-4
GEOM_MIN_NEAR_FRAC = 1e-5

# Internal same-distribution validation split from training cases.
# This split is used for tuning/early stopping because it preserves the same
# AoA/time/particle-count distribution as training more closely than a held-out
# angle-only validation set.

#Check out what these are? and what are angle only validation set?
USE_DUAL_SPLIT_PROTOCOL = True
VAL_ID_FRACTION_FROM_TRAIN_CASES = 0.2
VAL_ID_MIN_FRAMES_PER_TRAIN_CASE = 8
VAL_ID_FRAME_STRIDE = 5
VAL_ID_FRAME_OFFSET = 2

# Conditioning channels that are allowed to be constant by design for a setup.
# Example: freestream_y is exactly zero when inflow is in x-z plane.
CONDITIONING_ALLOWED_CONSTANT_CHANNELS: set = set()


# Basic helpers

FRAME_RE = re.compile(r"(\d+)(?!.*\d)")


def ensure_dir(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p


def frame_id(path: Path) -> str:
    m = FRAME_RE.search(path.stem)
    return m.group(1).zfill(6) if m else path.stem


def as_xyz(a: np.ndarray) -> np.ndarray:
    a = np.asarray(a)
    if a.ndim == 2 and a.shape[1] == 3:
        return a.astype(np.float64)
    if a.ndim == 2 and a.shape[0] == 3:
        return a.T.astype(np.float64)
    raise ValueError(f"Cannot parse xyz from shape={a.shape}")


def as_vec_field(a: np.ndarray) -> np.ndarray:
    a = np.asarray(a)
    if a.ndim == 4 and a.shape[-1] == 3:
        return a.astype(np.float64)
    if a.ndim == 4 and a.shape[0] == 3:
        return np.moveaxis(a, 0, -1).astype(np.float64)
    if a.ndim == 2 and a.shape[1] == 3:
        return a.astype(np.float64)
    if a.ndim == 2 and a.shape[0] == 3:
        return a.T.astype(np.float64)
    raise ValueError(f"Cannot parse vector field from shape={a.shape}")


def read_h5_selected(path: Path, key_map: Dict[str, str]) -> Dict[str, np.ndarray]:
    out: Dict[str, np.ndarray] = {}
    with h5py.File(path, "r") as f:
        for out_key, in_key in key_map.items():
            if in_key not in f:
                raise KeyError(f"{path.name}: missing key {in_key}")
            out[out_key] = np.asarray(f[in_key])
    return out


def read_field_grid_h5(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Read task2 field-domain grid coordinates and velocity."""
    with h5py.File(path, "r") as f:
        if "nodes" not in f:
            raise KeyError(f"{path.name}: missing grid-coordinate dataset 'nodes'")
        if "U" not in f:
            raise KeyError(f"{path.name}: missing velocity dataset 'U'")
        coords = as_xyz(np.asarray(f["nodes"]))
        velocity = as_xyz(np.asarray(f["U"]))
    if coords.shape[0] != velocity.shape[0]:
        raise ValueError(
            f"{path.name}: nodes and U have different point counts: "
            f"{coords.shape[0]} vs {velocity.shape[0]}"
        )
    return coords.astype(np.float32), velocity.astype(np.float32)


def _fit_scalar(arr: np.ndarray, n: int, default: float) -> np.ndarray:
    x = np.asarray(arr).reshape(-1)
    if x.size == 0:
        return np.full(n, default, dtype=np.float64)
    if x.size < n:
        out = np.full(n, default, dtype=np.float64)
        out[: x.size] = x
        return out
    return x[:n].astype(np.float64)


def _rows_from_pair_ids(pair_ranges: List[Tuple], pair_ids: np.ndarray) -> np.ndarray:
    chunks = []
    for i in pair_ids:
        _, _, _, s, e, _ = pair_ranges[int(i)]
        chunks.append(np.arange(int(s), int(e), dtype=np.int64))
    return np.concatenate(chunks) if chunks else np.zeros((0,), dtype=np.int64)


def _validate_case_split(all_cases: List[str]) -> None:
    if len(all_cases) == 0:
        raise ValueError(
            "No cases discovered from merged frames. This usually means raw-data path/pattern mismatch. "
            "Check RAW_ROOT and INPUT/OUTPUT patterns."
        )
    all_set = set(all_cases)
    tr, va, te = set(TRAIN_CASES), set(VAL_CASES), set(TEST_CASES)
    if tr & va or tr & te or va & te:
        raise ValueError("TRAIN_CASES / VAL_CASES / TEST_CASES must be disjoint")
    unknown = (tr | va | te) - all_set
    if unknown:
        raise ValueError(f"Split includes unknown cases: {sorted(unknown)}")
    uncovered = all_set - (tr | va | te)
    if uncovered:
        raise ValueError(f"Some cases are not assigned to any split: {sorted(uncovered)}")


ACTIVE_CASE_METADATA: Dict[str, Dict[str, Any]] = {}
ACTIVE_CONDITIONING_CHANNEL_NAMES: List[str] = []


def _load_case_metadata_overrides() -> Tuple[Dict[str, Dict[str, Any]], Dict[str, Any]]:
    if not CASE_METADATA_PATH.exists():
        return {}, {}
    payload = json.loads(CASE_METADATA_PATH.read_text())
    if not isinstance(payload, dict):
        raise ValueError(f"CASE_METADATA_PATH must contain a JSON object: {CASE_METADATA_PATH}")
    defaults = {}
    for key in ["_defaults", "defaults", "__defaults__"]:
        if key in payload and isinstance(payload[key], dict):
            defaults = dict(payload[key])
            break
    out: Dict[str, Dict[str, Any]] = {}
    for k, v in payload.items():
        if str(k) in {"_defaults", "defaults", "__defaults__"}:
            continue
        out[str(k)] = dict(v) if isinstance(v, dict) else {}
    return out, defaults


def _resolve_raw_root() -> Path:
    env_raw = os.environ.get("RAW_ROOT", "").strip()
    if env_raw:
        p = Path(env_raw)
        if p.exists() and p.is_dir():
            return p
        raise FileNotFoundError(
            f"RAW_ROOT is set but invalid: {p}. "
            "Fix the env var or unset it."
        )

    for cand in RAW_ROOT_CANDIDATES:
        c = Path(cand)
        if c.exists() and c.is_dir():
            return c
    tried = ", ".join([str(Path(c)) for c in RAW_ROOT_CANDIDATES])
    raise FileNotFoundError(
        "Could not locate Task-1 dataset root. Tried: "
        f"{tried}. Update RAW_ROOT or mount the external drive."
    )


def _resolve_field_root() -> Path:
    env_raw = os.environ.get("FIELD_ROOT", os.environ.get("TASK2_ROOT", "")).strip()
    if env_raw:
        p = Path(env_raw)
        if p.exists() and p.is_dir():
            return p
        raise FileNotFoundError(
            f"FIELD_ROOT/TASK2_ROOT is set but invalid: {p}. "
            "Fix the env var or unset it."
        )

    for cand in FIELD_ROOT_CANDIDATES:
        c = Path(cand)
        if c.exists() and c.is_dir():
            return c
    tried = ", ".join([str(Path(c)) for c in FIELD_ROOT_CANDIDATES])
    raise FileNotFoundError(
        "Could not locate Task-2 field-grid root. Tried: "
        f"{tried}. Update FIELD_ROOT/TASK2_ROOT or mount the external drive."
    )


def _parse_task1_case_name(case: str) -> Optional[Dict[str, float]]:
    m = TASK1_CASE_RE.match(str(case))
    if not m:
        return None
    return {
        "aoa_deg": float(m.group("aoa")),
        "magVinf": float(m.group("speed")),
        "particles_per_step": float(m.group("particles")),
    }


def _expected_particles_per_step_for_aoa(aoa_deg: float) -> int:
    """Return the intended particle-shedding resolution for a generated case."""
    aoa_key = int(round(float(aoa_deg)))
    return int(EXPECTED_PARTICLES_PER_STEP_BY_AOA.get(aoa_key, DEFAULT_PARTICLES_PER_STEP))


def _case_has_expected_particle_count(case: str) -> Tuple[bool, str]:
    """Check that folder naming matches the intended resolution plan.

    Task-1 no longer treats higher-particle-count cases as super-resolution.
    All accepted Task-1 particle datasets therefore default to 1p unless an
    explicit override is added later.
    """
    parsed = _parse_task1_case_name(case)
    if parsed is None:
        return False, "case name does not match Task-1 naming convention"
    observed = int(round(float(parsed["particles_per_step"])))
    expected = _expected_particles_per_step_for_aoa(float(parsed["aoa_deg"]))
    if observed != expected:
        return (
            False,
            f"expected {expected}p for AoA {parsed['aoa_deg']:g}, found {observed}p",
        )
    return True, "ok"


def _discover_task1_case_ids(root: Path) -> List[str]:
    if not AUTO_DISCOVER_TASK1_CASES:
        return [str(x) for x in DATASET_IDS if str(x).strip()]

    out: List[str] = []
    skipped_resolution: List[Tuple[str, str]] = []
    skipped_ignored_aoa: List[str] = []
    for p in sorted(root.iterdir()):
        if not p.is_dir():
            continue
        parsed = _parse_task1_case_name(p.name)
        if parsed is None:
            continue
        aoa = int(round(float(parsed["aoa_deg"])))
        if aoa in IGNORE_AOA_DEGREES:
            skipped_ignored_aoa.append(p.name)
            continue
        ok_resolution, why_resolution = _case_has_expected_particle_count(p.name)
        if not ok_resolution:
            skipped_resolution.append((p.name, why_resolution))
            continue
        if len(list(p.glob(DYNAMIC_PARTICLE_H5_PATTERN))) == 0:
            continue
        out.append(p.name)
    if skipped_resolution:
        print("[data] skipped case folders with unintended particle resolution:")
        for name, why in skipped_resolution:
            print(f"  - {name}: {why}")
    if skipped_ignored_aoa:
        print("[data] skipped ignored AoA case folders:")
        for name in skipped_ignored_aoa:
            print(f"  - {name}")
    if not out:
        raise RuntimeError(
            f"No Task-1 case folders found in {root}. "
            f"Expected names like 10deg_static_airfoil_10u_1p and files matching {DYNAMIC_PARTICLE_H5_PATTERN}."
        )
    return out


def _assign_case_splits_from_names(case_ids: List[str]) -> None:
    """Populate TRAIN_CASES/VAL_CASES/TEST_CASES from the AoA encoded in folder names."""
    if not AUTO_ASSIGN_SPLITS_FROM_CASE_NAMES:
        return

    global TRAIN_CASES, VAL_CASES, TEST_CASES
    train, val, test, unassigned = [], [], [], []
    for case in sorted(case_ids):
        parsed = _parse_task1_case_name(case)
        if parsed is None:
            unassigned.append(case)
            continue
        aoa = int(round(float(parsed["aoa_deg"])))
        if aoa in IGNORE_AOA_DEGREES:
            continue
        if aoa in TRAIN_AOA_DEGREES:
            train.append(case)
        elif aoa in VAL_AOA_DEGREES:
            val.append(case)
        elif aoa in TEST_AOA_DEGREES:
            test.append(case)
        else:
            unassigned.append(case)

    if unassigned:
        raise ValueError(
            "Some discovered cases do not match TRAIN_AOA_DEGREES / VAL_AOA_DEGREES / TEST_AOA_DEGREES: "
            + ", ".join(unassigned)
        )

    TRAIN_CASES = train
    VAL_CASES = val
    TEST_CASES = test


def _test_case_role_from_metadata(meta: Dict[str, Any]) -> str:
    """Classify test cases into the experiment role used in plots/reports."""
    aoa = int(round(float(meta["aoa_deg"])))
    if aoa in TEST_UNSEEN_AOA_DEGREES:
        return "testing_unseen_angle"
    if aoa in TEST_NORMAL_AOA_DEGREES:
        return "testing_normal"
    return "testing_other"


def _resolve_case_metadata(meta: Dict[str, Any]) -> Tuple[Optional[Dict[str, Any]], str]:
    """Resolve one case metadata entry into canonical form.

    Supported input forms:
    - Explicit:
      {"aoa_deg": 20, "freestream": [u, v, w], "dt": 0.001}
    - Derived freestream from AoA + speed:
      {"aoa_deg": 20, "magVinf": 49.7, "dt": 0.001}
    - Derived dt from total time:
      {"aoa_deg": 20, "magVinf": 49.7, "nsteps": 200, "ttot_constant": 100.0}
      where dt = (ttot_constant / magVinf) / nsteps
    - Alternate total-time form:
      {"aoa_deg": 20, "magVinf": 49.7, "nsteps": 200, "ttot_seconds": 0.5}
      where dt = ttot_seconds / nsteps
    """
    # AOA is mandatory.
    if "aoa_deg" not in meta or meta["aoa_deg"] is None:
        return None, "missing aoa_deg"
    try:
        aoa_deg = float(meta["aoa_deg"])
    except Exception:
        return None, "aoa_deg not numeric"
    if not np.isfinite(aoa_deg):
        return None, "aoa_deg non-finite"

    # Resolve freestream.
    fs = meta.get("freestream", None)
    mag_vinf = meta.get("magVinf", None)
    if fs is None:
        if mag_vinf is None:
            return None, "missing freestream and magVinf"
        try:
            mag_vinf = float(mag_vinf)
        except Exception:
            return None, "magVinf not numeric"
        if not np.isfinite(mag_vinf) or mag_vinf <= 0.0:
            return None, "magVinf must be finite and >0"
        # FLOWUnsteady convention used in user sim setup:
        # Vinf = magVinf * [cosd(AOA), 0, sind(AOA)]
        rad = np.deg2rad(aoa_deg)
        fs_arr = np.asarray(
            [mag_vinf * np.cos(rad), 0.0, mag_vinf * np.sin(rad)],
            dtype=np.float64,
        )
    else:
        try:
            fs_arr = np.asarray(fs, dtype=np.float64).reshape(-1)
        except Exception:
            return None, "freestream not numeric"
        if fs_arr.shape[0] != 3:
            return None, "freestream must have 3 components"
        if not np.all(np.isfinite(fs_arr)):
            return None, "freestream has non-finite values"
        # If user provided freestream but not speed, infer speed for dt formula path.
        if mag_vinf is None:
            mag_vinf = float(np.linalg.norm(fs_arr))
        else:
            try:
                mag_vinf = float(mag_vinf)
            except Exception:
                return None, "magVinf not numeric"

    # Resolve dt.
    dt_raw = meta.get("dt", None)
    if dt_raw is not None:
        try:
            dt = float(dt_raw)
        except Exception:
            return None, "dt not numeric"
        if not np.isfinite(dt) or dt <= 0.0:
            return None, "dt must be finite and >0"
    else:
        nsteps = meta.get("nsteps", None)
        if nsteps is None:
            return None, "missing dt and nsteps"
        try:
            nsteps = int(nsteps)
        except Exception:
            return None, "nsteps not integer"
        if nsteps <= 0:
            return None, "nsteps must be >0"

        if "ttot_seconds" in meta and meta["ttot_seconds"] is not None:
            try:
                ttot_seconds = float(meta["ttot_seconds"])
            except Exception:
                return None, "ttot_seconds not numeric"
            if not np.isfinite(ttot_seconds) or ttot_seconds <= 0.0:
                return None, "ttot_seconds must be finite and >0"
            dt = ttot_seconds / float(nsteps)
        elif "ttot_constant" in meta and meta["ttot_constant"] is not None:
            try:
                ttot_constant = float(meta["ttot_constant"])
            except Exception:
                return None, "ttot_constant not numeric"
            if not np.isfinite(ttot_constant) or ttot_constant <= 0.0:
                return None, "ttot_constant must be finite and >0"
            if mag_vinf is None:
                return None, "magVinf required for ttot_constant formula"
            if not np.isfinite(float(mag_vinf)) or float(mag_vinf) <= 0.0:
                return None, "magVinf must be finite and >0 for ttot_constant formula"
            ttot_seconds = float(ttot_constant) / float(mag_vinf)
            dt = ttot_seconds / float(nsteps)
        else:
            return None, "missing dt and no supported dt formula keys"

    resolved = {
        "aoa_deg": float(aoa_deg),
        "freestream": fs_arr.astype(np.float64).reshape(3),
        "dt": float(dt),
        "magVinf": float(np.linalg.norm(fs_arr)),
    }
    return resolved, "ok"


def _prepare_case_metadata(all_cases: List[str]) -> Dict[str, Dict[str, Any]]:
    merged: Dict[str, Dict[str, Any]] = {str(k): dict(v) for k, v in CASE_METADATA.items()}
    overrides, defaults = _load_case_metadata_overrides()
    merged.update(overrides)

    # Ensure all required cases exist in the metadata mapping.
    # For the new Task-1 naming scheme this is the built-in metadata table:
    #   <AoA>deg_static_airfoil_<speed>u_<particles>p
    # Example:
    #   20deg_static_airfoil_10u_1p ->
    #   aoa_deg=20, magVinf=10, dt=DEFAULT_TASK1_DT.
    # _resolve_case_metadata() then converts magVinf + AoA into the same
    # FLOWUnsteady freestream convention used in simulation.jl:
    #   Vinf = magVinf * [cosd(AOA), 0, sind(AOA)].
    for c in all_cases:
        if str(c) not in merged:
            parsed = _parse_task1_case_name(str(c))
            if parsed is None:
                merged[str(c)] = {}
            else:
                merged[str(c)] = {
                    "aoa_deg": float(parsed["aoa_deg"]),
                    "magVinf": float(parsed["magVinf"]),
                    "dt": DEFAULT_TASK1_DT,
                    "particles_per_step": int(parsed["particles_per_step"]),
                }

    active: Dict[str, Dict[str, Any]] = {}
    missing: Dict[str, str] = {}
    for case in all_cases:
        meta = dict(defaults)
        meta.update(merged.get(case, {}) or {})
        resolved, why = _resolve_case_metadata(meta)
        if resolved is None:
            missing[str(case)] = why
            continue
        active[str(case)] = {
            "aoa_deg": float(resolved["aoa_deg"]),
            "freestream": np.asarray(resolved["freestream"], dtype=np.float64).reshape(3),
            "dt": float(resolved["dt"]),
            "magVinf": float(resolved["magVinf"]),
            "particles_per_step": int(round(float(meta.get("particles_per_step", 1)))),
        }

    if USE_EXPLICIT_CONDITIONING and STRICT_METADATA_VALIDATION and missing:
        details = ", ".join([f"{k}({v})" for k, v in sorted(missing.items())])
        raise ValueError(
            "Conditioning is enabled but metadata is incomplete/invalid for cases: "
            f"{details}. Fill CASE_METADATA or provide {CASE_METADATA_PATH}."
        )
    if missing and not USE_EXPLICIT_CONDITIONING:
        print(f"[meta] conditioning disabled, allowing missing metadata for cases: {sorted(missing.keys())}")
    elif missing and not STRICT_METADATA_VALIDATION:
        print(f"[meta] warning: metadata missing for cases: {sorted(missing.keys())}")

    return active


def _case_meta(case: str) -> Dict[str, object]:
    meta = ACTIVE_CASE_METADATA.get(str(case), None)
    if meta is None:
        # This fallback is only valid when conditioning is disabled.
        if USE_EXPLICIT_CONDITIONING and STRICT_METADATA_VALIDATION:
            raise ValueError(f"Missing validated metadata for case={case}")
        return {
            "aoa_deg": 0.0,
            "freestream": np.asarray([0.0, 0.0, 0.0], dtype=np.float64),
            "dt": 1.0,
            "particles_per_step": 1,
        }
    return {
        "aoa_deg": float(meta["aoa_deg"]),
        "freestream": np.asarray(meta["freestream"], dtype=np.float64).reshape(3),
        "dt": float(meta["dt"]),
        "particles_per_step": int(meta.get("particles_per_step", 1)),
    }


_VTK_GEOM_CACHE: Dict[str, Tuple[np.ndarray, np.ndarray, object]] = {}
_GEOM_BACKEND_NOTICE_PRINTED = False


def _normalize_rows(v: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """Normalize row-vectors safely."""
    n = np.linalg.norm(v, axis=1, keepdims=True)
    n = np.maximum(n, eps)
    return v / n


def _point_normals_from_cells(points: np.ndarray, cells: List[np.ndarray]) -> np.ndarray:
    """Estimate point normals by averaging adjacent cell normals."""
    normals = np.zeros_like(points, dtype=np.float64)
    for c in cells:
        if c.size < 3:
            continue
        p0 = points[int(c[0])]
        p1 = points[int(c[1])]
        p2 = points[int(c[2])]
        n = np.cross(p1 - p0, p2 - p0)
        mag = np.linalg.norm(n)
        if mag <= 1e-12:
            continue
        n = n / mag
        normals[c.astype(np.int64)] += n

    nz = np.linalg.norm(normals, axis=1) > 1e-12
    if np.any(nz):
        normals[nz] = _normalize_rows(normals[nz])
    return normals


def _load_legacy_vtk_ascii(vp: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Read VTK legacy ASCII points/cells and estimate point normals.

    This is a dependency-light fallback for environments where `pyvista`
    is unavailable. It is sufficient for common FLOWUnsteady wing VTK files.
    """
    txt = vp.read_text(errors="ignore").splitlines()

    npts = None
    p0 = None
    for i, ln in enumerate(txt):
        s = ln.strip()
        if s.upper().startswith("POINTS "):
            parts = s.split()
            if len(parts) < 2:
                raise ValueError(f"Invalid POINTS line in {vp}")
            npts = int(parts[1])
            p0 = i + 1
            break
    if npts is None or p0 is None:
        raise ValueError(f"Could not find POINTS section in {vp}")

    vals: List[float] = []
    i = p0
    while i < len(txt) and len(vals) < 3 * npts:
        s = txt[i].strip()
        if s == "" or s.startswith("#"):
            i += 1
            continue
        head = s.split()[0].upper()
        if head in {
            "CELLS",
            "CELL_TYPES",
            "POINT_DATA",
            "CELL_DATA",
            "SCALARS",
            "VECTORS",
            "LOOKUP_TABLE",
            "FIELD",
        }:
            break
        vals.extend(float(x) for x in s.split())
        i += 1
    if len(vals) < 3 * npts:
        raise ValueError(f"Incomplete POINTS data in {vp}")
    pts = np.asarray(vals[: 3 * npts], dtype=np.float64).reshape(npts, 3)

    cells: List[np.ndarray] = []
    for j, ln in enumerate(txt):
        s = ln.strip()
        if s.upper().startswith("CELLS "):
            parts = s.split()
            if len(parts) < 2:
                break
            ncells = int(parts[1])
            k = j + 1
            for _ in range(ncells):
                if k >= len(txt):
                    break
                row = txt[k].strip().split()
                k += 1
                if not row:
                    continue
                m = int(row[0])
                if m <= 0:
                    continue
                idx = np.asarray([int(x) for x in row[1 : 1 + m]], dtype=np.int64)
                if idx.size >= 3:
                    cells.append(idx)
            break

    if len(cells) == 0:
        normals = np.zeros_like(pts)
    else:
        normals = _point_normals_from_cells(pts, cells)
    return pts, normals


def _load_vtk_geom(vtk_path: str):
    """Load/cached VTK points and normals.

    Returns (points, normals, tree_or_none). Normals can be zeros if unavailable.
    """
    if not vtk_path:
        return None, None, None
    if vtk_path in _VTK_GEOM_CACHE:
        return _VTK_GEOM_CACHE[vtk_path]

    vp = Path(vtk_path)
    if not vp.exists():
        _VTK_GEOM_CACHE[vtk_path] = (None, None, None)
        return _VTK_GEOM_CACHE[vtk_path]

    try:
        if PYVISTA_AVAILABLE:
            mesh = pv.read(str(vp))
            pts = np.asarray(mesh.points, dtype=np.float64)
            nrm = None

            for k in ["Normals", "normal", "normals"]:
                if hasattr(mesh, "point_data") and k in mesh.point_data:
                    cand = np.asarray(mesh.point_data[k], dtype=np.float64)
                    if cand.ndim == 2 and cand.shape[1] == 3 and cand.shape[0] == pts.shape[0]:
                        nrm = cand
                        break

            # If normals are missing in file, estimate from mesh cells.
            if nrm is None or np.linalg.norm(nrm, axis=1).max(initial=0.0) <= 1e-12:
                if hasattr(mesh, "faces") and mesh.faces is not None and mesh.faces.size > 0:
                    faces = mesh.faces
                    cells: List[np.ndarray] = []
                    i = 0
                    while i < len(faces):
                        m = int(faces[i])
                        if m >= 3:
                            cells.append(np.asarray(faces[i + 1 : i + 1 + m], dtype=np.int64))
                        i += 1 + m
                    nrm = _point_normals_from_cells(pts, cells) if len(cells) > 0 else np.zeros_like(pts)
                else:
                    # Last-resort parser for legacy ASCII VTK.
                    pts2, nrm2 = _load_legacy_vtk_ascii(vp)
                    pts, nrm = pts2, nrm2
        else:
            pts, nrm = _load_legacy_vtk_ascii(vp)

        tree = cKDTree(pts) if (SCIPY_AVAILABLE and pts is not None and pts.size > 0) else None
        _VTK_GEOM_CACHE[vtk_path] = (pts, nrm, tree)
    except Exception as e:
        # Keep running, but expose a clear warning once so the user can fix setup.
        global _GEOM_BACKEND_NOTICE_PRINTED
        if not _GEOM_BACKEND_NOTICE_PRINTED:
            print(f"[geom] warning: failed to load VTK geometry ({e}). Geometry channels will be zeros for affected frames.")
            _GEOM_BACKEND_NOTICE_PRINTED = True
        _VTK_GEOM_CACHE[vtk_path] = (None, None, None)

    return _VTK_GEOM_CACHE[vtk_path]


def _particle_geometry_features(xyz: np.ndarray, vtk_path: str, n: int) -> Dict[str, np.ndarray]:
    """Compute per-particle geometry channels by nearest surface query."""
    zeros = np.zeros(n, dtype=np.float64)
    if not USE_GEOMETRY_CHANNELS:
        return {
            "geom_dist": zeros,
            "geom_nx": zeros,
            "geom_ny": zeros,
            "geom_nz": zeros,
            "geom_body_near": zeros,
        }

    pts, nrm, tree = _load_vtk_geom(vtk_path)
    if pts is None or nrm is None or len(pts) == 0:
        return {
            "geom_dist": zeros,
            "geom_nx": zeros,
            "geom_ny": zeros,
            "geom_nz": zeros,
            "geom_body_near": zeros,
        }

    q = xyz[:n]
    if tree is not None:
        dist, idx = tree.query(q, k=1)
    else:
        diff = q[:, None, :] - pts[None, :, :]
        d2 = np.sum(diff * diff, axis=2)
        idx = np.argmin(d2, axis=1)
        dist = np.sqrt(np.min(d2, axis=1))

    nn = nrm[idx]
    body_near = (dist <= GEOMETRY_NEAR_THRESHOLD).astype(np.float64)
    return {
        "geom_dist": np.asarray(dist, dtype=np.float64),
        "geom_nx": np.asarray(nn[:, 0], dtype=np.float64),
        "geom_ny": np.asarray(nn[:, 1], dtype=np.float64),
        "geom_nz": np.asarray(nn[:, 2], dtype=np.float64),
        "geom_body_near": body_near,
    }


def _print_geometry_channel_stats(X: np.ndarray, feature_names: List[str], tag: str) -> None:
    """Print compact geometry-channel statistics for sanity checks."""
    if not USE_GEOMETRY_CHANNELS:
        print(f"[{tag}] geometry channels disabled.")
        return
    print(f"[{tag}] geometry channel stats:")
    all_zero = True
    for k in GEOMETRY_CHANNEL_NAMES:
        if k not in feature_names:
            print(f"  - {k}: missing from feature_names")
            continue
        j = feature_names.index(k)
        v = X[:, j]
        vmin = float(np.min(v))
        vmax = float(np.max(v))
        vmean = float(np.mean(v))
        nnz = int(np.count_nonzero(v))
        print(f"  - {k:14s} min={vmin:.6g} max={vmax:.6g} mean={vmean:.6g} nnz={nnz}")
        if nnz > 0:
            all_zero = False
    if all_zero:
        print(
            f"[{tag}] warning: all geometry channels are zero. "
            "Check VTK paths, VTK parser backend, and GEOMETRY_NEAR_THRESHOLD."
        )


def _geometry_frame_report(case: str, frame: str, n_particles: int, vtk_path: str, geom_feat: Dict[str, np.ndarray]) -> Dict[str, Any]:
    dist = np.asarray(geom_feat.get("geom_dist", np.zeros(n_particles)), dtype=np.float64)
    nx = np.asarray(geom_feat.get("geom_nx", np.zeros(n_particles)), dtype=np.float64)
    ny = np.asarray(geom_feat.get("geom_ny", np.zeros(n_particles)), dtype=np.float64)
    nz = np.asarray(geom_feat.get("geom_nz", np.zeros(n_particles)), dtype=np.float64)
    near = np.asarray(geom_feat.get("geom_body_near", np.zeros(n_particles)), dtype=np.float64)
    nrm_mag = np.sqrt(nx * nx + ny * ny + nz * nz)

    return {
        "case": str(case),
        "frame": str(frame),
        "n_particles": int(n_particles),
        "vtk_path": str(vtk_path),
        "geom_dist_mean": float(np.mean(dist)) if dist.size else 0.0,
        "geom_dist_p95": float(np.percentile(dist, 95)) if dist.size else 0.0,
        "geom_dist_nonzero_frac": float(np.mean(dist > 0.0)) if dist.size else 0.0,
        "geom_body_near_frac": float(np.mean(near > 0.5)) if near.size else 0.0,
        "normal_mag_mean": float(np.mean(nrm_mag)) if nrm_mag.size else 0.0,
        "normal_mag_var": float(np.var(nrm_mag)) if nrm_mag.size else 0.0,
        "normal_nx_var": float(np.var(nx)) if nx.size else 0.0,
        "normal_ny_var": float(np.var(ny)) if ny.size else 0.0,
        "normal_nz_var": float(np.var(nz)) if nz.size else 0.0,
    }


def _geometry_case_summary(entries: List[Dict[str, Any]]) -> Dict[str, Any]:
    by_case: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for e in entries:
        by_case[str(e["case"])].append(e)
    out: Dict[str, Any] = {}
    for case, arr in sorted(by_case.items()):
        dist_nonzero = np.asarray([a["geom_dist_nonzero_frac"] for a in arr], dtype=np.float64)
        near_frac = np.asarray([a["geom_body_near_frac"] for a in arr], dtype=np.float64)
        nx_var = np.asarray([a["normal_nx_var"] for a in arr], dtype=np.float64)
        ny_var = np.asarray([a["normal_ny_var"] for a in arr], dtype=np.float64)
        nz_var = np.asarray([a["normal_nz_var"] for a in arr], dtype=np.float64)
        out[case] = {
            "n_frames": int(len(arr)),
            "geom_dist_nonzero_frac_mean": float(np.mean(dist_nonzero)),
            "geom_body_near_frac_mean": float(np.mean(near_frac)),
            "normal_var_mean": float(np.mean(nx_var + ny_var + nz_var)),
        }
    return out


def _validate_geometry_report(entries: List[Dict[str, Any]]) -> None:
    if not USE_GEOMETRY_CHANNELS or len(entries) == 0:
        return
    case_sum = _geometry_case_summary(entries)
    bad_cases: List[str] = []
    for case, s in case_sum.items():
        if s["geom_dist_nonzero_frac_mean"] < GEOM_MIN_NONZERO_FRAC:
            bad_cases.append(f"{case}:geom_dist_nonzero={s['geom_dist_nonzero_frac_mean']:.3e}")
        if s["geom_body_near_frac_mean"] < GEOM_MIN_NEAR_FRAC:
            bad_cases.append(f"{case}:near_frac={s['geom_body_near_frac_mean']:.3e}")
    if bad_cases:
        msg = "Geometry channels appear collapsed for cases -> " + ", ".join(bad_cases)
        if STRICT_GEOMETRY_QA:
            raise RuntimeError(msg)
        print(f"[geom] warning: {msg}")


def _frame_is_usable(n_particles: int) -> Tuple[bool, str]:
    if n_particles < int(MIN_PARTICLES_PER_FRAME):
        return False, f"n_particles<{MIN_PARTICLES_PER_FRAME}"
    return True, "ok"


def _train_id_val_id_split_by_case(frame_ranges: List[Tuple], train_frame_ids: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Split training cases into training and same-distribution validation frames.

    We keep whole test cases held out, but for model selection we need a
    validation split whose AoA/time/particle-count distribution resembles the
    training distribution. Taking the last 20% of each trajectory would make
    validation contain mostly late, high-particle-count frames. Instead, this
    uses an interleaved stride inside every training case:

        validation = frames[offset::stride]
        training   = all remaining frames

    This is for optimizer/model selection only. The separate held-out angle,
    super-resolution, and unseen-angle test sets remain the final generalization
    checks.
    """
    if not USE_DUAL_SPLIT_PROTOCOL or train_frame_ids.size == 0:
        return train_frame_ids, np.zeros((0,), dtype=np.int64)

    by_case: Dict[str, List[int]] = defaultdict(list)
    for i in train_frame_ids.tolist():
        case = str(frame_ranges[int(i)][0])
        by_case[case].append(int(i))

    train_out: List[int] = []
    val_id_out: List[int] = []
    for case, ids in sorted(by_case.items()):
        ids_sorted = sorted(ids, key=lambda j: int(frame_ranges[int(j)][1]))
        n = len(ids_sorted)
        if n <= 1:
            train_out.extend(ids_sorted)
            continue

        stride = max(int(VAL_ID_FRAME_STRIDE), 2)
        offset = min(max(int(VAL_ID_FRAME_OFFSET), 0), stride - 1)
        val_ids = ids_sorted[offset::stride]

        # Keep at least a small validation sample per case, but never consume
        # all frames from a case.
        min_val = min(max(int(VAL_ID_MIN_FRAMES_PER_TRAIN_CASE), 1), max(n - 1, 1))
        if len(val_ids) < min_val:
            needed = min_val - len(val_ids)
            existing = set(val_ids)
            supplement = [j for j in ids_sorted if j not in existing][:needed]
            val_ids.extend(supplement)

        val_set = set(val_ids)
        train_ids = [j for j in ids_sorted if j not in val_set]
        if not train_ids:
            train_ids = ids_sorted[:-1]
            val_ids = ids_sorted[-1:]

        val_id_out.extend(val_ids)
        train_out.extend(train_ids)

    return np.asarray(sorted(train_out), dtype=np.int64), np.asarray(sorted(val_id_out), dtype=np.int64)


def _split_stats_from_rows(
    Y: np.ndarray,
    frame_ranges: List[Tuple],
    split_ids: np.ndarray,
    split_name: str,
) -> Dict[str, Any]:
    if split_ids.size == 0:
        return {"split": split_name, "n_frames": 0}
    rows = []
    case_counts: Dict[str, int] = defaultdict(int)
    n_particles = []
    for i in split_ids.tolist():
        case, _, s, e, n = frame_ranges[int(i)]
        s = int(s)
        e = int(e)
        rows.append(np.arange(s, e, dtype=np.int64))
        case_counts[str(case)] += 1
        n_particles.append(int(n))
    idx = np.concatenate(rows) if rows else np.zeros((0,), dtype=np.int64)
    yy = Y[idx]
    vel = np.linalg.norm(yy[:, :3], axis=1)
    grd = np.linalg.norm(yy[:, 3:], axis=1)

    def _q(v: np.ndarray, q: float) -> float:
        return float(np.quantile(v, q)) if v.size else float("nan")

    return {
        "split": split_name,
        "n_frames": int(split_ids.size),
        "case_counts": dict(case_counts),
        "n_particles": {
            "min": int(np.min(n_particles)),
            "median": float(np.median(n_particles)),
            "p90": float(np.quantile(n_particles, 0.9)),
            "max": int(np.max(n_particles)),
        },
        "u_mag": {
            "mean": float(np.mean(vel)),
            "p50": _q(vel, 0.5),
            "p95": _q(vel, 0.95),
            "max": float(np.max(vel)),
        },
        "grad_u_mag": {
            "mean": float(np.mean(grd)),
            "p50": _q(grd, 0.5),
            "p95": _q(grd, 0.95),
            "max": float(np.max(grd)),
        },
    }


def _assert_conditioning_variance(X: np.ndarray, feature_names: List[str], train_rows: np.ndarray) -> None:
    if not USE_EXPLICIT_CONDITIONING:
        return
    dead = []
    informative = []
    for ch in ACTIVE_CONDITIONING_CHANNEL_NAMES:
        if ch not in feature_names:
            dead.append(f"{ch}(missing)")
            continue
        idx = feature_names.index(ch)
        v = float(np.var(X[train_rows, idx]))
        if v <= 1e-12:
            # Some channels are expected to be constant in specific setups.
            if ch in CONDITIONING_ALLOWED_CONSTANT_CHANNELS:
                print(f"[cond] info: {ch} is constant by design; allowing it.")
                continue
            dead.append(f"{ch}(var~0)")
        else:
            informative.append(ch)

    # Only fail if non-allowed channels are dead and no informative channel remains.
    if dead and len(informative) == 0:
        raise RuntimeError(
            "Conditioning channels are non-informative on train rows (after allowed constants): "
            + ", ".join(dead)
            + ". Provide valid metadata or disable conditioning."
        )
    if dead and len(informative) > 0:
        print(
            "[cond] warning: some conditioning channels are constant, "
            f"but proceeding because informative channels exist: {informative}. "
            f"Constant channels: {dead}"
        )


# ==============================================================================
# Stage-1 merge
# ==============================================================================
INPUT_KEYS = {
    "particle_xyz": "X",
    "Gamma_vec": "Gamma",
    "velocity": "velocity",
    "velocity_gradient_x": "velocity_gradient_x",
    "velocity_gradient_y": "velocity_gradient_y",
    "velocity_gradient_z": "velocity_gradient_z",
    "sigma": "sigma",
    "circulation": "circulation",
    "vol": "vol",
    "static": "static",
}
def _merge_particle_payloads(dynamic_payload: Dict[str, np.ndarray], static_payload: Optional[Dict[str, np.ndarray]]) -> Dict[str, np.ndarray]:
    """Concatenate wake particles and static body particles for one frame."""
    if static_payload is None or not INCLUDE_STATIC_PARTICLES:
        return {k: np.asarray(v) for k, v in dynamic_payload.items()}

    out: Dict[str, np.ndarray] = {}
    for key in dynamic_payload:
        a = np.asarray(dynamic_payload[key])
        b = np.asarray(static_payload[key])
        if a.ndim == 0 or b.ndim == 0:
            out[key] = a
        else:
            out[key] = np.concatenate([a, b], axis=0)
    return out


def merge_frames() -> List[Path]:
    if not RAW_ROOT.exists():
        raise FileNotFoundError(
            f"RAW_ROOT does not exist: {RAW_ROOT}. "
            "Mount/check external drive or update RAW_ROOT."
        )

    ensure_dir(MERGED_ROOT)
    merged: List[Path] = []
    missing_dataset_dirs: List[str] = []

    for ds in DATASET_IDS:
        root = RAW_ROOT / ds
        if not root.exists():
            missing_dataset_dirs.append(str(root))
            continue

        dynamic_h5 = sorted(root.glob(DYNAMIC_PARTICLE_H5_PATTERN))
        static_h5 = sorted(root.glob(STATIC_PARTICLE_H5_PATTERN))
        vtk = {frame_id(p): p for p in sorted(root.glob(VTK_PATTERN))}

        dynamic_map = {frame_id(p): p for p in dynamic_h5}
        static_map = {frame_id(p): p for p in static_h5}
        common = sorted(dynamic_map)
        print(
            f"[merge] {ds}: pfield={len(dynamic_h5)} "
            f"static_pfield={len(static_h5)} vtk={len(vtk)} paired={len(common)}"
        )

        out_dir = ensure_dir(MERGED_ROOT / ds)
        for fr in common:
            pin = dynamic_map[fr]
            pstatic = static_map.get(fr, None)
            dynamic_payload = read_h5_selected(pin, INPUT_KEYS)
            static_payload = read_h5_selected(pstatic, INPUT_KEYS) if pstatic is not None else None
            payload = _merge_particle_payloads(dynamic_payload, static_payload)

            payload["source_dataset"] = np.asarray(ds, dtype=object)
            payload["frame_id"] = np.asarray(fr, dtype=object)
            payload["source_vtk_path"] = np.asarray(str(vtk.get(fr, "")), dtype=object)
            payload["source_input_h5_path"] = np.asarray(str(pin), dtype=object)
            payload["source_static_h5_path"] = np.asarray("" if pstatic is None else str(pstatic), dtype=object)
            payload["source_output_h5_path"] = np.asarray("", dtype=object)

            op = out_dir / f"{ds}__frame_{fr}.npz"
            np.savez_compressed(op, **payload)
            merged.append(op)

    merged = sorted(merged)
    print("[merge] total merged:", len(merged))
    if len(merged) == 0:
        msg = (
            "No paired frames were merged. "
            f"RAW_ROOT={RAW_ROOT}, DATASET_IDS={DATASET_IDS}, "
            f"DYNAMIC_PARTICLE_H5_PATTERN={DYNAMIC_PARTICLE_H5_PATTERN}, "
            f"STATIC_PARTICLE_H5_PATTERN={STATIC_PARTICLE_H5_PATTERN}."
        )
        if missing_dataset_dirs:
            msg += " Missing dataset directories include: " + ", ".join(missing_dataset_dirs[:8])
        raise RuntimeError(msg)
    return merged


# ==============================================================================
# Task-1 preprocessing: EVOLUTION DATASET (x_t -> delta_state)
# ==============================================================================

def _state_from_frame(data: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
    xyz = as_xyz(data["particle_xyz"])
    gamma = as_xyz(data["Gamma_vec"])
    n = xyz.shape[0]
    sigma = _fit_scalar(data["sigma"], n, 1e-2)

    return {
        "x": xyz[:, 0],
        "y": xyz[:, 1],
        "z": xyz[:, 2],
        "Gamma_x": gamma[:, 0],
        "Gamma_y": gamma[:, 1],
        "Gamma_z": gamma[:, 2],
        "sigma": sigma,
    }


def _feature_matrix_from_state(
    state: Dict[str, np.ndarray],
    velocity: np.ndarray,
    n: int,
    phase: float,
    aoa_deg: float,
    freestream: np.ndarray,
    geom_feat: Dict[str, np.ndarray] = None,
) -> np.ndarray:
    feat = {
        "x": state["x"][:n],
        "y": state["y"][:n],
        "z": state["z"][:n],
        "Gamma_x": state["Gamma_x"][:n],
        "Gamma_y": state["Gamma_y"][:n],
        "Gamma_z": state["Gamma_z"][:n],
        "sigma": state["sigma"][:n],
        "u_x": velocity[:n, 0],
        "u_y": velocity[:n, 1],
        "u_z": velocity[:n, 2],
    }
    # Optional context features are only added if requested.
    if "phase" in PARTICLE_INPUT_FEATURES:
        feat["phase"] = np.full(n, phase, dtype=np.float64)
    if "angle_of_attack" in PARTICLE_INPUT_FEATURES:
        feat["angle_of_attack"] = np.full(n, aoa_deg, dtype=np.float64)
    if "freestream_x" in PARTICLE_INPUT_FEATURES:
        feat["freestream_x"] = np.full(n, float(freestream[0]), dtype=np.float64)
    if "freestream_y" in PARTICLE_INPUT_FEATURES:
        feat["freestream_y"] = np.full(n, float(freestream[1]), dtype=np.float64)
    if "freestream_z" in PARTICLE_INPUT_FEATURES:
        feat["freestream_z"] = np.full(n, float(freestream[2]), dtype=np.float64)
    if geom_feat is not None:
        for gk in GEOMETRY_CHANNEL_NAMES:
            if gk in PARTICLE_INPUT_FEATURES:
                gv = geom_feat.get(gk, None)
                if gv is None:
                    feat[gk] = np.zeros(n, dtype=np.float64)
                else:
                    feat[gk] = np.asarray(gv[:n], dtype=np.float64)
    else:
        for gk in GEOMETRY_CHANNEL_NAMES:
            if gk in PARTICLE_INPUT_FEATURES:
                feat[gk] = np.zeros(n, dtype=np.float64)
    return np.stack([feat[k] for k in PARTICLE_INPUT_FEATURES], axis=1).astype(np.float32)


def _state_matrix(state: Dict[str, np.ndarray], n: int) -> np.ndarray:
    return np.stack([state[k][:n] for k in STATE_NAMES], axis=1).astype(np.float32)


def _normalize_channels_rows(x: np.ndarray, train_rows: np.ndarray):
    mean = np.mean(x[train_rows], axis=0, keepdims=True)
    std = np.std(x[train_rows], axis=0, keepdims=True)
    std = np.maximum(std, 1e-8)
    xn = ((x - mean) / std).astype(np.float32)
    return mean.astype(np.float32), std.astype(np.float32), xn


def _case_split_label(case: str) -> str:
    if case in TRAIN_CASES:
        return "train"
    if case in VAL_CASES:
        return "val"
    if case in TEST_CASES:
        return "test"
    raise ValueError(f"Case {case} is not assigned in TRAIN_CASES/VAL_CASES/TEST_CASES")


def build_particle_evolution_dataset(merged: List[Path]) -> Path:
    by_case: Dict[str, List[Path]] = {}
    for p in merged:
        by_case.setdefault(p.parent.name, []).append(p)
    for c in by_case:
        by_case[c] = sorted(by_case[c], key=lambda x: frame_id(x))

    field_root = _resolve_field_root()
    field_h5_by_case: Dict[str, Dict[int, Path]] = {}
    for case in sorted(by_case.keys()):
        case_field_root = field_root / case
        if not case_field_root.exists():
            field_h5_by_case[case] = {}
            continue
        field_h5_by_case[case] = {
            frame_id(path): path
            for path in sorted(case_field_root.glob(FIELD_H5_PATTERN))
        }
        print(f"[field] {case}: fdom frames={len(field_h5_by_case[case])}")

    def field_grid_for_pair(case: str, frame_t: object) -> Optional[Tuple[np.ndarray, np.ndarray]]:
        try:
            fr_int = int(float(str(frame_t)))
        except Exception:
            return None
        key = (case, fr_int)
        path = field_h5_by_case.get(key[0], {}).get(key[1])
        if path is None:
            return None
        return read_field_grid_h5(path)

    all_cases = sorted(by_case.keys())
    _validate_case_split(all_cases)

    # Pre-load all frame states per case
    case_frames: Dict[str, List[Dict[str, object]]] = {}
    for case in all_cases:
        meta = _case_meta(case)
        plist = by_case[case]
        T = len(plist)
        if T < 2:
            print(f"[warn] case={case} has <2 frames; skipping")
            continue

        fr_list: List[Dict[str, object]] = []
        for i, p in enumerate(plist):
            with np.load(p, allow_pickle=True) as d:
                data = {k: d[k] for k in d.files}
            state = _state_from_frame(data)
            velocity = as_xyz(data["velocity"])
            fr = str(np.asarray(data["frame_id"]).reshape(-1)[0])
            vtk_path = str(np.asarray(data.get("source_vtk_path", "")).reshape(-1)[0])
            phase = 0.0 if T <= 1 else float(i) / float(T - 1)
            fr_list.append(
                {
                    "frame_id": fr,
                    "state": state,
                    "velocity": velocity,
                    "phase": phase,
                    "path": str(p),
                    "vtk_path": vtk_path,
                }
            )
        case_frames[case] = fr_list

    rows_x: List[np.ndarray] = []
    rows_delta: List[np.ndarray] = []
    rows_next: List[np.ndarray] = []
    field_query_coords_by_pair: List[np.ndarray] = []
    field_velocity_by_pair: List[np.ndarray] = []
    skipped_pairs_missing_field = 0

    pair_ranges: List[Tuple] = []
    pair_contexts: List[Dict[str, object]] = []

    # rollout ground-truth container (case-wise sequence of aligned states)
    rollout_cases: List[str] = []
    rollout_true_states: List[np.ndarray] = []
    rollout_phases: List[np.ndarray] = []
    rollout_dts: List[float] = []

    start = 0
    for case in sorted(case_frames.keys()):
        meta = _case_meta(case)
        fr_list = case_frames[case]
        T = len(fr_list)

        # Build rollout ground truth by consistent truncation to minimum particle count across full case.
        nmin_case = min(len(fr["state"]["x"]) for fr in fr_list)
        true_seq = []
        phase_seq = []
        for fr in fr_list:
            st = fr["state"]
            true_seq.append(_state_matrix(st, nmin_case))
            phase_seq.append(float(fr["phase"]))

        rollout_cases.append(case)
        rollout_true_states.append(np.stack(true_seq, axis=0).astype(np.float32))  # [T, Nmin, 7]
        rollout_phases.append(np.asarray(phase_seq, dtype=np.float32))
        rollout_dts.append(float(meta["dt"]))

        # Build consecutive training pairs: x_t -> delta_t.
        for i in range(T - 1):
            curr = fr_list[i]
            nxt = fr_list[i + 1]
            field_grid = field_grid_for_pair(case, curr["frame_id"])
            if field_grid is None:
                skipped_pairs_missing_field += 1
                continue

            s0 = curr["state"]
            s1 = nxt["state"]

            n0 = len(s0["x"])
            n1 = len(s1["x"])
            n = min(n0, n1)
            if n <= 0:
                continue

            curr_xyz = np.stack([s0["x"][:n], s0["y"][:n], s0["z"][:n]], axis=1)
            geom_feat = _particle_geometry_features(curr_xyz, str(curr.get("vtk_path", "")), n)

            x_feat = _feature_matrix_from_state(
                state=s0,
                velocity=np.asarray(curr["velocity"], dtype=np.float32),
                n=n,
                phase=float(curr["phase"]),
                aoa_deg=float(meta["aoa_deg"]),
                freestream=np.asarray(meta["freestream"], dtype=np.float64),
                geom_feat=geom_feat,
            )

            st0 = _state_matrix(s0, n)
            st1 = _state_matrix(s1, n)
            delta = st1 - st0
            velocity_current = np.asarray(curr["velocity"], dtype=np.float32)[:n]
            velocity_next = np.asarray(nxt["velocity"], dtype=np.float32)[:n]
            delta_u = velocity_next - velocity_current
            target = np.concatenate([delta, delta_u], axis=1).astype(np.float32)

            end = start + n
            pair_ranges.append((case, curr["frame_id"], nxt["frame_id"], start, end, n))
            pair_contexts.append(
                {
                    "case": case,
                    "frame_t": curr["frame_id"],
                    "frame_tp1": nxt["frame_id"],
                    "start": start,
                    "end": end,
                    "n_particles": n,
                    "phase_t": float(curr["phase"]),
                    "phase_tp1": float(nxt["phase"]),
                    "aoa_deg": float(meta["aoa_deg"]),
                    "freestream": [float(v) for v in np.asarray(meta["freestream"]).reshape(-1)],
                    "dt": float(meta["dt"]),
                }
            )

            rows_x.append(x_feat.astype(np.float32))
            rows_delta.append(target)
            rows_next.append(st1.astype(np.float32))
            grid_coords, grid_velocity = field_grid
            field_query_coords_by_pair.append(grid_coords.astype(np.float32))
            field_velocity_by_pair.append(grid_velocity.astype(np.float32))
            start = end

    if not rows_x:
        raise RuntimeError("No Task-1 pairs were built. Check frame availability and metadata.")

    X = np.concatenate(rows_x, axis=0).astype(np.float32)
    Y_delta = np.concatenate(rows_delta, axis=0).astype(np.float32)
    Y_next = np.concatenate(rows_next, axis=0).astype(np.float32)

    n_pairs = len(pair_ranges)
    field_query_coords = np.zeros((n_pairs, MAX_FIELD_QUERY_POINTS, 3), dtype=np.float32)
    targets_velocity_field = np.zeros((n_pairs, MAX_FIELD_QUERY_POINTS, 3), dtype=np.float32)
    field_query_mask = np.zeros((n_pairs, MAX_FIELD_QUERY_POINTS), dtype=bool)
    for pair_id, (query_coords, velocity_values) in enumerate(zip(field_query_coords_by_pair, field_velocity_by_pair)):
        n_query = min(int(query_coords.shape[0]), int(MAX_FIELD_QUERY_POINTS))
        if n_query <= 0:
            continue
        if query_coords.shape[0] > n_query:
            # Deterministic coverage of the field grid for this pair. The
            # training Dataset can still randomly subsample further each epoch.
            picked = np.linspace(0, query_coords.shape[0] - 1, n_query, dtype=np.int64)
        else:
            picked = np.arange(n_query, dtype=np.int64)
        field_query_coords[pair_id, :n_query, :] = query_coords[picked, :]
        targets_velocity_field[pair_id, :n_query, :] = velocity_values[picked, :]
        field_query_mask[pair_id, :n_query] = True

    # Case-based split at pair level
    pair_split_train = np.array([i for i, r in enumerate(pair_ranges) if _case_split_label(r[0]) == "train"], dtype=np.int64)
    pair_split_val = np.array([i for i, r in enumerate(pair_ranges) if _case_split_label(r[0]) == "val"], dtype=np.int64)
    pair_split_test = np.array([i for i, r in enumerate(pair_ranges) if _case_split_label(r[0]) == "test"], dtype=np.int64)

    train_rows = _rows_from_pair_ids(pair_ranges, pair_split_train)
    val_rows = _rows_from_pair_ids(pair_ranges, pair_split_val)
    test_rows = _rows_from_pair_ids(pair_ranges, pair_split_test)

    # Normalize per feature using TRAIN rows only.
    in_mean, in_std, Xn = _normalize_channels_rows(X, train_rows)
    out_mean, out_std, Yn_delta = _normalize_channels_rows(Y_delta, train_rows)

    train_field_values = targets_velocity_field[pair_split_train][field_query_mask[pair_split_train]]
    if train_field_values.size == 0:
        raise RuntimeError("No field-reconstruction query points were available in the training split.")
    field_mean = np.mean(train_field_values, axis=0, keepdims=True).astype(np.float32)
    field_std = np.maximum(np.std(train_field_values, axis=0, keepdims=True), 1e-8).astype(np.float32)
    targets_velocity_field_norm = ((targets_velocity_field - field_mean.reshape(1, 1, 3)) / field_std.reshape(1, 1, 3)).astype(np.float32)

    # Next-state normalization for optional analysis (not primary training target).
    next_mean = np.mean(Y_next[train_rows], axis=0, keepdims=True)
    next_std = np.maximum(np.std(Y_next[train_rows], axis=0, keepdims=True), 1e-8)
    Yn_next = ((Y_next - next_mean) / next_std).astype(np.float32)
    coord_cols = [PARTICLE_INPUT_FEATURES.index(k) for k in ("x", "y", "z")]
    coord_min = np.min(X[:, coord_cols], axis=0).astype(np.float32)
    coord_span = np.maximum(np.ptp(X[:, coord_cols], axis=0), 1e-8).astype(np.float32)

    out_path = OUT_ROOT / "particle_evolution_dataset.npz"
    np.savez_compressed(
        out_path,
        # core supervised data
        inputs_t=X,
        targets_delta=Y_delta,
        query_coords=field_query_coords,
        targets_velocity_field=targets_velocity_field,
        field_query_mask=field_query_mask,
        field_query_source=np.asarray("task2_static_airfoil_fdom_grid", dtype=object),
        field_root=np.asarray(str(field_root), dtype=object),
        targets_next_state=Y_next,
        inputs_t_norm=Xn,
        targets_delta_norm=Yn_delta,
        targets_velocity_field_norm=targets_velocity_field_norm,
        targets_next_state_norm=Yn_next,
        # naming
        feature_names=np.asarray(PARTICLE_INPUT_FEATURES, dtype=object),
        state_names=np.asarray(STATE_NAMES, dtype=object),
        target_names=np.asarray(TARGET_DELTA_NAMES, dtype=object),
        field_target_names=np.asarray(FIELD_TARGET_NAMES, dtype=object),
        # pair indexing
        pair_ranges=np.asarray(pair_ranges, dtype=object),
        pair_contexts=np.asarray(pair_contexts, dtype=object),
        train_pair_ids=pair_split_train,
        val_pair_ids=pair_split_val,
        test_pair_ids=pair_split_test,
        train_rows=train_rows,
        val_rows=val_rows,
        test_rows=test_rows,
        # rollout ground truth
        rollout_cases=np.asarray(rollout_cases, dtype=object),
        rollout_true_states=np.asarray(rollout_true_states, dtype=object),
        rollout_phases=np.asarray(rollout_phases, dtype=object),
        rollout_dts=np.asarray(rollout_dts, dtype=np.float32),
        # split metadata
        train_cases=np.asarray(TRAIN_CASES, dtype=object),
        val_cases=np.asarray(VAL_CASES, dtype=object),
        test_cases=np.asarray(TEST_CASES, dtype=object),
        case_metadata=np.asarray(CASE_METADATA, dtype=object),
        use_geometry_channels=np.asarray(USE_GEOMETRY_CHANNELS),
        geometry_channel_names=np.asarray(GEOMETRY_CHANNEL_NAMES, dtype=object),
        # normalization
        in_mean=in_mean.astype(np.float32),
        in_std=in_std.astype(np.float32),
        out_mean=out_mean.astype(np.float32),
        out_std=out_std.astype(np.float32),
        field_mean=field_mean.astype(np.float32),
        field_std=field_std.astype(np.float32),
        next_mean=next_mean.astype(np.float32),
        next_std=next_std.astype(np.float32),
        coord_min=coord_min,
        coord_span=coord_span,
        max_field_query_points=np.asarray(MAX_FIELD_QUERY_POINTS, dtype=np.int64),
    )

    # Rich console summary for sanity checks.
    print("\n[task1] Particle evolution dataset built")
    print("  inputs_t shape            :", X.shape)
    print("  targets_delta shape       :", Y_delta.shape)
    print("  query_coords shape        :", field_query_coords.shape)
    print("  targets_velocity_field    :", targets_velocity_field.shape)
    print("  skipped pairs no field    :", skipped_pairs_missing_field)
    print("  targets_next_state shape  :", Y_next.shape)
    print("  n_pairs                   :", len(pair_ranges))
    print("  n_rollout_cases           :", len(rollout_cases))
    print("  feature_names             :", PARTICLE_INPUT_FEATURES)
    print("  use_geometry_channels     :", USE_GEOMETRY_CHANNELS)
    print("  target_names              :", TARGET_DELTA_NAMES)
    print("  split(train/val/test) pairs:", len(pair_split_train), len(pair_split_val), len(pair_split_test))
    print("  split(train/val/test) rows :", len(train_rows), len(val_rows), len(test_rows))
    print("  train/val/test cases      :", TRAIN_CASES, VAL_CASES, TEST_CASES)
    _print_geometry_channel_stats(X, PARTICLE_INPUT_FEATURES, "task1-delta")

    return out_path



# ==============================================================================
# Main
# ==============================================================================

def main() -> None:
    global ACTIVE_CASE_METADATA
    global ACTIVE_CONDITIONING_CHANNEL_NAMES
    global RAW_ROOT
    global DATASET_IDS

    RAW_ROOT = _resolve_raw_root()
    DATASET_IDS = _discover_task1_case_ids(RAW_ROOT)
    _assign_case_splits_from_names(DATASET_IDS)

    ensure_dir(OUT_ROOT)
    ensure_dir(MERGED_ROOT)

    ACTIVE_CASE_METADATA = _prepare_case_metadata([str(c) for c in DATASET_IDS])
    ACTIVE_CONDITIONING_CHANNEL_NAMES = list(CONDITIONING_CHANNEL_NAMES) if USE_EXPLICIT_CONDITIONING else []
    print("[data] resolved RAW_ROOT:", RAW_ROOT)
    print("[data] discovered datasets:", DATASET_IDS)
    print("[data] split cases train/validation/testing:", TRAIN_CASES, VAL_CASES, TEST_CASES)
    print("[meta] validated metadata cases:", sorted(ACTIVE_CASE_METADATA.keys()))
    print("[meta] active conditioning channels:", ACTIVE_CONDITIONING_CHANNEL_NAMES)

    merged = merge_frames()

    mode = str(TASK1_TARGET_MODE).lower()
    if mode != "delta":
        raise ValueError("TASK1_TARGET_MODE must be 'delta'")
    particle_evolution_path = build_particle_evolution_dataset(merged)

    summary = {
        "raw_root": str(RAW_ROOT),
        "datasets": DATASET_IDS,
        "n_merged_frames": len(merged),
        "task1_target_mode": mode,
        "task1_particle_evolution_dataset": None if particle_evolution_path is None else str(particle_evolution_path),
        "use_explicit_conditioning": USE_EXPLICIT_CONDITIONING,
        "conditioning_channel_names": CONDITIONING_CHANNEL_NAMES if USE_EXPLICIT_CONDITIONING else [],
        "conditioning_active_channel_names": ACTIVE_CONDITIONING_CHANNEL_NAMES,
        "use_geometry_channels": USE_GEOMETRY_CHANNELS,
        "geometry_channel_names": GEOMETRY_CHANNEL_NAMES,
        "geometry_near_threshold": GEOMETRY_NEAR_THRESHOLD,
        "strict_geometry_qa": STRICT_GEOMETRY_QA,
        "geom_min_nonzero_frac": GEOM_MIN_NONZERO_FRAC,
        "geom_min_near_frac": GEOM_MIN_NEAR_FRAC,
        "min_particles_per_frame": MIN_PARTICLES_PER_FRAME,
        "dual_split_enabled": USE_DUAL_SPLIT_PROTOCOL,
        "val_id_fraction_from_train_cases": VAL_ID_FRACTION_FROM_TRAIN_CASES,
        "val_id_min_frames_per_train_case": VAL_ID_MIN_FRAMES_PER_TRAIN_CASE,
        "pyvista_available": PYVISTA_AVAILABLE,
        "scipy_available": SCIPY_AVAILABLE,
        "train_cases": TRAIN_CASES,
        "val_cases": VAL_CASES,
        "test_cases": TEST_CASES,
    }
    (OUT_ROOT / "preprocess_summary.json").write_text(json.dumps(summary, indent=2))
    print("\n[done] preprocess summary")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
